//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdoc.Org.Uk.Championship.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mdoc.Org.Uk.Championship.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ClubForm_ChangeButton_Add {
            get {
                return ResourceManager.GetString("ClubForm_ChangeButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ClubForm_ChangeButton_Edit {
            get {
                return ResourceManager.GetString("ClubForm_ChangeButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Scores….
        /// </summary>
        internal static string Main_CalculateScoreRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_CalculateScoreRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string Main_CancelIfUnsavedChanges_Caption {
            get {
                return ResourceManager.GetString("Main_CancelIfUnsavedChanges_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to loss unsaved changes?.
        /// </summary>
        internal static string Main_CancelIfUnsavedChanges_Question {
            get {
                return ResourceManager.GetString("Main_CancelIfUnsavedChanges_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete….
        /// </summary>
        internal static string Main_DeleteClubMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_DeleteClubMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Main_DeleteClubToolStripMenuItemClick_ConfirmCaption {
            get {
                return ResourceManager.GetString("Main_DeleteClubToolStripMenuItemClick_ConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete….
        /// </summary>
        internal static string Main_DeleteRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_DeleteRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Main_DeleteRaceToolStripMenuItemClick_ConfirmOption {
            get {
                return ResourceManager.GetString("Main_DeleteRaceToolStripMenuItemClick_ConfirmOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string Main_DisplayException_Caption {
            get {
                return ResourceManager.GetString("Main_DisplayException_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download….
        /// </summary>
        internal static string Main_DownloadRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_DownloadRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit….
        /// </summary>
        internal static string Main_EditClubMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_EditClubMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit….
        /// </summary>
        internal static string Main_EditRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_EditRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Competitors….
        /// </summary>
        internal static string Main_FindCompetitorsRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_FindCompetitorsRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import….
        /// </summary>
        internal static string Main_ImportRaceMenuItem_Text {
            get {
                return ResourceManager.GetString("Main_ImportRaceMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Main_ShowError_Caption {
            get {
                return ResourceManager.GetString("Main_ShowError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string RaceForm_ChangeButton_Add {
            get {
                return ResourceManager.GetString("RaceForm_ChangeButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string RaceForm_ChangeButton_Edit {
            get {
                return ResourceManager.GetString("RaceForm_ChangeButton_Edit", resourceCulture);
            }
        }
    }
}
